library/book/urls.py
from django.urls import path
from . import  views

urlpatterns = [
    path("author/", views.author_read, name = "author_read"),
    path("author/create/", views.author_create, name = "author_create"),
    path("author/<int:id>/", views.author_update, name = "author_update"),
    path("author/<int:id>/delete/", views.author_delete, name = "author_delete"),

    path("genre/", views.genre_read, name = "genre_read"),
    path("genre/create/", views.genre_create, name = "genre_create"),
    path("genre/<int:id>/", views.genre_update, name = "genre_update"),
    path("genre/<int:id>/delete/", views.genre_delete, name = "genre_delete"),

    path("publisher/", views.publisher_read, name = "publisher_read"),
    path("publisher/create/", views.publisher_create, name = "publisher_create"),
    path("publisher/<int:id>/", views.publisher_update, name = "publisher_update"),
    path("publisher/<int:id>/delete/", views.publisher_delete, name = "publisher_delete"),

    path("book/", views.book_read, name = "book_read"),
    path("book/create/", views.book_create, name = "book_create"),
    path("book/<int:id>/", views.book_update, name = "book_update"),
    path("book/<int:id>/delete/", views.book_delete, name = "book_delete"),
]

'''

    path("create/", views.location_create, name = "location_create"),
    path("<int:id>", views.location_update, name = "location_update"),
    path("<int:id>/delete/", views.location_delete, name = "location_delete"),
'''

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # new
from django.conf.urls.static import static  # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include("register.urls")),
    path('user/', include("managementUser.urls")),
    path('location/', include("location.urls")),
    path('', include("book.urls")),
    path('borrow/', include("borrow.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

library/managementUser/urls.py
from django.urls import path
from . import  views

urlpatterns = [
    path("", views.user_read, name = "user_read"),
    path("<int:id>/", views.user_update, name = "user_update"),
    path("delete/<int:id>/", views.user_delete, name = "user_delete"),
]

library/managementUser/models.py
from django.db import models
from register.models import User
from location.models import library_location
# Create your models here.

class admin_library(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    library_location = models.ForeignKey(library_location, on_delete=models.CASCADE)
    decsription = models.CharField(max_length=200, null = True)
    is_active = models.BooleanField(default= True)

    def __str__(self):
        return "Admin # " + str(self.library_location.name)

library/register/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    ROLE_CHOICES = [
        ('user', 'User'),
        ('admin', 'Admin'),
        ('superadmin', 'Super Admin'),
    ]

    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='user')

    class Meta(AbstractUser.Meta):
       swappable = 'AUTH_USER_MODEL'
    

library/managementUser/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from register.models import User
from .form import form_edit_user, AdminLibraryForm
from .models import admin_library

#region ================================= USER MANAGEMENT AREA ==========================================================================

@login_required()
def user_read(response):
    if response.user.role != 'superadmin':
        return HttpResponseRedirect('/')
    data = User.objects.all()
    return render(response, "managementUser/user_read.html", {"data":data})

@login_required()
def user_update(response, id):
    #Autorisation
    if response.user.role != 'superadmin':
        return HttpResponseRedirect('/')

    data = get_object_or_404(User, id=id)
    data2 = admin_library.objects.filter(user=data).first()
    old_role = data.role
    form = form_edit_user(response.POST or None, instance=data)
    form2 = AdminLibraryForm(response.POST or None, instance=data2)

    if response.method =="POST":
        if form.is_valid():
            instance = form.save(commit=False)  

            # Delete admin_library, when role change from admin to another
            if old_role != instance.role and instance.role != 'admin':
                admin = get_object_or_404(admin_library, user = instance)
                admin.delete()

            # Save form2 (AdminLibraryForm) only if the role is 'admin'
            if instance.role == 'admin' and form2.is_valid():
                admin_library_instance = form2.save(commit=False) # Prevent premature saving
                admin_library_instance.user = instance
                
                if not admin_library_instance.decsription:
                    admin_library_instance.decsription = ''  # Set to None for empty strings
                
                admin_library_instance.save()

            instance.save()
            return redirect('user_read')

    return render(response, "managementUser/user_update.html", {"form":form, 'form2':form2})

@login_required()
def user_delete(response, id):
    user = get_object_or_404(User, id=id)
    
    # Check if the user has permission to delete this ToDoList item
    if response.user.role == 'superadmin':
        user.delete()
        return redirect('user_read')
    else:
        return HttpResponseRedirect('/')

#endregion ================================= USER MANAGEMENT AREA ==========================================================================

#region ================================= LIBRARY ADMIN AREA ==========================================================================



#endregion ================================= LIBRARY ADMIN AREA ==========================================================================

library/templates/managementUser/user_read.html
{% extends 'register/base.html'%}

{% block tittle %}
User
{% endblock %}

{% load crispy_forms_tags %}
{% block content %}

<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-8">
        <h1 class="m-0 text-dark">User List</h1>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>

<section class="content">
<div class="container-fluid">

<table id = "myTable" class="table table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Username</th>
        <th scope="col">Email</th>
        <th scope="col">Role</th>
        <th scope="col">Active</th>
        <th scope="col">Last Login</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
        {% for item in data %}
        {% with forloop.counter as n %}
        <tr>
            <th scope="row">{{ n }}</th>
            <td>{{ item.username }}</td>
            <td>{{ item.email }}</td>
            <td>{{ item.role }}</td>
            <td>{{ item.is_active }}</td>
            <td>{{ item.last_login }}</td>
            <td>
              <div class="btn-group">
                <a href="http://127.0.0.1:8000/user/{{item.id}}" class="btn btn-primary btn-sm">
                    <i class="nav-icon fas fa-edit"></i> Edit
                </a>
                <form method="POST" action="{% url 'user_delete' id=item.id %}">
                  {% csrf_token %}
                  <input type="hidden" name="is_delete" value="True">
                  <button type="submit" class="btn btn-danger btn-sm ml-1" onclick="return confirm('Anda Yakin?')">
                  <i class="nav-icon fas fa-trash"></i> Delete </button>
                </form>
            </div>
            </td>
        </tr>
        {% endwith %}
        {% endfor %}
    </tbody>
</table>

</div>
</section>


{% endblock %}

library/templates/managementUser/user_update.html
{% extends 'register/base.html'%}

{% block tittle %}
Edit user
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div id="admin-details" style="display: none;">
        {{ form2|crispy }}
    </div>
    <button type="submit" name="edit_user" value="edit_user" class="btn btn-success">Edit</button>
</form>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    // Async form2
    $(document).ready(function() {
        $('#id_role').change(function() {
            var selectedRole = $(this).val();
            if (selectedRole === 'admin') {
                $('#admin-details').show();
                $('#id_library_location').prop('required', true);
            } else {
                $('#admin-details').hide();
                $('#id_library_location').prop('required', false);
            }
        });

        $('#id_role').trigger('change');
    });
</script>
{% endblock %}